id: P001671
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG15922
  title: སྟག་ལུང་སྡོམ་གསུམ་རྒྱས་འབྲིང་བསྡུས་པ་ཕྱོགས་གཅིག་ཏུ་བསྒྲིགས་པ།
  author: ''
  volumes:
    6255eff2d51840fca14bb6626b41c439:
      image_group_id: I1KG15924
      title: ''
      volume_number: 1
      total_pages: 426
