id: ICA33D0DA
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-21T19:38:47+00:00'
last_modified: '2022-06-07T13:58:05.539256+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG15922
  title: སྟག་ལུང་སྡོམ་གསུམ་རྒྱས་འབྲིང་བསྡུས་པ་ཕྱོགས་གཅིག་ཏུ་བསྒྲིགས་པ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    B3F8:
      image_group_id: I1KG15924
      title: ''
      total_pages: 426
      order: 1
      base_file: B3F8.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
